server:
  port: 8010
  servlet:
    context-path: /
    encoding:
      charset: utf-8


spring:
  application:
    name: "todo-api"
  datasource:
    url: jdbc:mysql://db-p0faj.pub-cdb.ntruss.com/mjconnect?allowPublicKeyRetrieval=true
    username: semyung
    password: tpaud123$


  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
