server:
  port: 8010
  servlet:
    context-path: /
    encoding:
      charset: utf-8


spring:
  application:
    name: "todo-api"
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydb?allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
